@startuml wacky-races
participant UI
participant service
autonumber
UI -> service: GET /races/{num_races}
UI <[#blue]- service: some races
newpage
UI -> service: GET /race/{race_id}
UI <[#blue]- service: race details
@enduml
